### ISSUE TITLE
Bing KeyError

### ISSUE THREAD

**Issue by csecht** [sujitmandal/scrape-search-engine#4]
The Bing engine raises a KeyError: 'href' on occasion. I haven't found a general pattern that initiates it; it seems random. 
Example search: 'trout'. (userAgent = 'Firefox/92.0')
Google, Duckduckgo, and Yahoo have not raised the error for identical searches. 
I've stepped around it with try...except..., but it would be nice to not exclude Bing from some searches.

**Comment by sujitmandal** [comment]
@csecht 
then try with Chrome.
